CREATE TABLE passengers (
	id SERIAL PRIMARY KEY,
	"firstName" VARCHAR(100),
	"lastName" VARCHAR(100)
);

CREATE TABLE cities (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) UNIQUE
);

CREATE TABLE flights (
	id SERIAL PRIMARY KEY,
	origin INTEGER REFERENCES cities(id) ON DELETE CASCADE,
	destination INTEGER REFERENCES cities(id) ON DELETE CASCADE,
	date TIMESTAMP
);

CREATE TABLE travels (
	id SERIAL PRIMARY KEY,
	"passengerId" INTEGER REFERENCES passengers(id) ON DELETE CASCADE,
	"flightId" INTEGER REFERENCES flights(id) ON DELETE CASCADE
);
